name: Devsecops

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  zbuduj-obraz-dockera:
    runs-on: ubuntu-latest

    steps:
      - name: Sprawdź repozytorium
        uses: actions/checkout@v4.2.2

      - name: Budowanie obrazu aplikacji w dockerze
        run: docker build -t juice-shop-projekt .
