name: Skan DAST (ZAP)

on:
  push:
    branches: [skandevsec]

jobs:
  skanowanie-dast-zap:
    runs-on: ubuntu-latest
    container:
      image: docker:24.0.5-dind
      options: --privileged
      env:
        DOCKER_TLS_CERTDIR: ""

    steps:
      - name: Instalacja Docker CLI
        run: |
          apk add --no-cache docker-cli

      - name: Uruchomienie Docker daemon
        run: |
          dockerd-entrypoint.sh &
          sleep 10

      - name: Sprawdzenie repozytorium
        uses: actions/checkout@v4.2.2

      - name: Budowa obrazu aplikacji
        run: docker build -t juice-shop-projekt .

      - name: Uruchomienie kontenera juice-shop-projekt
        run: |
          docker run -d \
            --network host \
            --name juice-shop \
            -p 3000:3000 \
            juice-shop-projekt

      - name: Sleep na 30
        run: sleep 30

      - name: Uruchomienie skanu OWASP ZAP
        continue-on-error: true
        run: |
          docker run --rm \
            --network host \
            -v $PWD:/zap/wrk/:rw \
            ghcr.io/zaproxy/zaproxy:stable \
            zap-baseline.py -t http://localhost:3000
