name: Skan DAST (ZAP)

on:
  push:
    branches: [skandevsec]

jobs:
  dast-zap:
    runs-on: ubuntu-latest
    container:
      image: docker:24.0.5-dind
      options: --privileged
      env:
        DOCKER_TLS_CERTDIR: ""

    steps:
      - name: Instalacja Docker CLI, curl i docker-compose
        run: |
          apk add --no-cache docker-cli docker-compose curl

      - name: Uruchom Docker daemon
        run: |
          dockerd-entrypoint.sh &
          sleep 10

      - name: Zbuduj obraz dockera
        run: docker build -t juice-shop-projekt .

      - name: Uruchom oficjalny obraz Juice Shop
        run: |
          docker run -d \
            --network host \
            --name juice-shop \
            -p 3000:3000 \
            juice-shop-projekt

      - name: Poczekaj na aplikację
        run: sleep 30

      - name: Uruchom skan OWASP ZAP
        run: |
          docker run --rm \
            --network host \
            -v $PWD:/zap/wrk/:rw \
            ghcr.io/zaproxy/zaproxy:stable \
            zap-baseline.py -t http://localhost:3000
