name: Skan DAST (ZAP)

on:
  push:
    branches: [skandevsec]
  pull_request:
    branches: [skandevsec]

jobs:
  budowa-obrazu-i-skan-dast:
    runs-on: ubuntu-latest
    container:
      image: docker:24.0.5-dind
      options: --privileged
      env:
        DOCKER_TLS_CERTDIR: ""

    steps:
      - name: Instalacja Dockera CLI
        run: |
          apk add --no-cache docker-cli curl

      - name: Uruchomienie Dockera Daemona w tle
        run: |
          dockerd-entrypoint.sh &
          sleep 10

      - name: Sprawdzenie repozytorium
        uses: actions/checkout@v4.2.2

      - name: Budowa obrazu aplikacji
        run: docker build -t juice-shop-projekt .

      - name: Uruchomienie aplikacji ze zbudowanego obrazu
        run: docker run -d -p 3000:3000 --name jsp juice-shop-projekt

      - name: Sleep na 15
        run: sleep 15

      - name: Uruchomienie skanu DAST ZAP
        run: |
          docker run --network host ghcr.io/zaproxy/zaproxy:stable zap-full-scan.py -t http://localhost:3000
