name: Skan trivy i Push do GHCR

on:
  push:
    branches: [skandevsec]

jobs:
  budowa-skan-i-wypchniecie:
    runs-on: ubuntu-latest

    steps:
      - name: Sprawdzenie kodu
        uses: actions/checkout@v4.2.2

      - name: Budowa obrazu dockera
        run: docker build -t juice-shop-projekt:latest .

      - name: Skan obrazu z wykorzystaniem Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: juice-shop-projekt:latest
          format: json
          exit-code: 0
          ignore-unfixed: true
          severity: HIGH,CRITICAL
          output: trivy-report.txt

      - name: Pokazanie raportu
        run: cat trivy-report.txt

      - name: Zapisanie raportu jako artefakt
        uses: actions/upload-artifact@v4
        with:
          name: trivy-report-prior-release
          path: trivy-report.txt

      - name: Logowanie do GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: MegaBit016
          password: ${{ secrets.GHCR_PAT }}

      - name: Tagowanie i push do GHCR
        run: |
          IMAGE=ghcr.io/megabit016/juice-shop-projekt:latest
          docker tag juice-shop-projekt:latest $IMAGE
          docker push $IMAGE
